
# Date:      2011/07/11 17:55
# Author:    Jan Faigl
#


include Mk/libs.mk
include Mk/flags.mk
#CXXFLAGS+= -g 
#
OBJS=coords.o gui.o math_common.o my_defines.o heuristic_types.o mesh_object.o dijkstra.o  prm.o rrt.o blender_loader.o dataset_loader_obst.o obst_op_loader.o vns_obst_op_path.o vns_obst_op_solver.o 
SUBDIRS=opendubins
TARGETS=vns_prm_pop 
OBJ_DIR=obj

include Mk/comrob.mk
